### ISSUE TITLE
Hesita Ansible collection

### ISSUE THREAD

**Issue by ulvida** [jeazyee/ansible-role-hestiacp#3]
Hi @jeazyee, hi everybody,

We have started [`cielito.hestia` ansible collection](https://galaxy.ansible.com/ui/repo/published/cielito/hestia/) to go further Hestia CP installation, ensuring full configuration and eventually data provision. 

Presently the collection includes:
*  [`cielito.hestia.cp` role](https://galaxy.ansible.com/ui/repo/published/cielito/hestia/content/role/cp/), which is a fork of present role, included [as a git submodule of the repo](https://git.interior.edu.uy/cielito/hestia/-/tree/main/roles)
*  [`cielito.hestia.cluster` role](https://galaxy.ansible.com/ui/repo/published/cielito/hestia/content/role/cluster/) which configures several Hestia CP instances as a [hestia DNS cluster](https://hestiacp.com/docs/server-administration/dns.html).

Would you like to join efforts, using and developing one single code? Or, if you will be no longer maintaining this repo, would you like to archive it and link to the collection as it's successor?

**Comment by jeazyee** [comment]
Hey @ulvida, I have added you as collaborator. Feel free to do with it whatever you want.

**Comment by ulvida** [comment]
Thanks for your trust, @jeazyee.
